version: '3.8'

services:
  backend:
    build:
      context: ../Leken
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/crm
    volumes:
      - ../Leken:/app
    command: python -m fastapi dev main_sqlmodel.py --host 0.0.0.0 --port 8011

  frontend:
    build: .
    ports:
      - "3007:3007"
    environment:
      - VITE_API_URL=http://localhost:8011
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: